spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud_learning_setting
        username: root
        password: 12345678
    liquibase:
        change-log: classpath:/db/sql/change.sql
    main:
        allow-bean-definition-overriding: true
